site_name: EnviroTyping
site_description: EnviroTyping Project Documentation
repo_url: https://github.com/TACC/EnviroTyping
theme: readthedocs
docs_dir: 'doc_files/docs'
pages:
- Home: index.md
- 'Genomes to Fields Project': project_scope.md
- 'Premium Manual': manual.md
- Workflow:
    - 'Getting Started': 'workflow/getting_started.md'
    - 'Benchmark Known Truth': 'workflow/benchmark.md'
    - 'Creating G2F Datasets': 'workflow/datasets.md'
    - 'Small Real Data Analysis': 'workflow/toy_g2f.md'
    - 'Post hoc Analysis': 'workflow/profile_by_group.md'
    - 'Interactive App': 'workflow/profile_by_group_app.md'
- Tutorials:
    - 'Getting Started With High Performance Computing': 'tutorials/hpc.md'
    - 'Launcher Module': 'tutorials/launcher_module.md'
- 'Updating the Docs': updating.md


site_author: 'Dave Hiltbrand'
